dedupe test.db create --params=32768,262144,2048,2 

dedupe test.db write --key=001 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=001 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=002 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=003 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=004 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=005 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=006 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=007 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=008 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=009 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=010 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=011 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=012 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=013 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=014 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=015 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=016 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=017 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=018 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=019 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=020 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=021 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=022 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=023 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=024 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=025 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=026 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=027 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=028 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=029 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=030 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=031 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=032 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=033 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=034 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=035 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=036 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=037 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=038 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=039 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=040 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=041 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=042 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=043 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=044 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=045 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=046 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=047 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=048 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=049 --chunks=chunks/ < samplefiles/kjv.txt
dedupe test.db write --key=050 --chunks=chunks/ < samplefiles/kjv.txt

dedupe test.db list --key=00 --idxstart=0 --results=100
